# Generated by Django 5.2.13 on 2026-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('ssh_user', models.CharField(max_length=120)),
                ('ssh_host', models.CharField(max_length=120)),
                ('ssh_key_path', models.CharField(blank=True, max_length=255)),
                ('conda_env', models.CharField(blank=True, max_length=120)),
                ('runner_python', models.CharField(blank=True, max_length=255)),
                ('project_root', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
