# Generated by Django 5.2.13 on 2026-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtarget',
            name='execution_mode',
            field=models.CharField(default='ssh', max_length=32),
        ),
    ]
