# Generated by Django 5.2.13 on 2026-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_root', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(default='pending', max_length=64)),
                ('completed_batches', models.PositiveIntegerField(default=0)),
                ('aggregate_label_counts', models.JSONField(blank=True, default=dict)),
                ('aggregate_approaches', models.JSONField(blank=True, default=dict)),
                ('orchestration_status_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
