# Generated by Django 5.2.13 on 2026-05-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approaches', '0001_initial'),
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default='', editable=False, max_length=64, unique=True)),
                ('experiment_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='gcs_bucket', max_length=64)),
                ('source_uri', models.CharField(max_length=255)),
                ('annotations_csv', models.CharField(max_length=255)),
                ('requested_slide_limit', models.PositiveIntegerField(default=0)),
                ('selected_slide_count', models.PositiveIntegerField(default=0)),
                ('label_counts', models.JSONField(blank=True, default=dict)),
                ('feature_extractor_candidates', models.JSONField(blank=True, default=list)),
                ('feature_extractor_used', models.CharField(blank=True, max_length=120)),
                ('tile_px', models.PositiveIntegerField(default=256)),
                ('tile_um', models.PositiveIntegerField(default=128)),
                ('max_tiles_per_slide', models.PositiveIntegerField(default=96)),
                ('n_folds', models.PositiveIntegerField(default=2)),
                ('n_repeats', models.PositiveIntegerField(default=2)),
                ('state', models.CharField(choices=[('matching_annotations', 'Matching annotations'), ('downloading_slides', 'Downloading slides'), ('extracting_tiles', 'Extracting tiles'), ('retrying_tiles', 'Retrying tiles'), ('generating_features', 'Generating features'), ('prepared', 'Prepared'), ('training_parallel', 'Training parallel'), ('completed', 'Completed'), ('failed', 'Failed')], default='matching_annotations', max_length=64)),
                ('remote_status_path', models.CharField(blank=True, max_length=255)),
                ('archive_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vm_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='vm.vmtarget')),
            ],
        ),
        migrations.CreateModel(
            name='RunApproachLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=64)),
                ('trainer_params', models.JSONField(blank=True, default=dict)),
                ('mean_auroc', models.FloatField(blank=True, null=True)),
                ('mean_f1_macro', models.FloatField(blank=True, null=True)),
                ('prediction_artifacts', models.JSONField(blank=True, default=dict)),
                ('metrics_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approach_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_links', to='approaches.approachtemplate')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approach_links', to='runs.run')),
            ],
            options={
                'unique_together': {('run', 'approach_template')},
            },
        ),
    ]
