# Generated by Django 5.2.13 on 2026-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='bundle_config_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='run',
            name='remote_launch_log_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='run',
            name='remote_pid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
